<a href="https://colab.research.google.com/github/aregueiraaraujo/Data-Analytics/blob/main/Data-Analytics%20/Sprint%207/Sprint_7_Nivel_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Nivel 1

Ejercicio 1: Selección de Personal

In [1]:
# Esta biblioteca permite impimir diccionarios en vertical para mejor visualización
import pprint

# La función de validación de datos comprueba si cada uno de los datos
# introducidos por el usuario se ajusta al formato de datos esperado
def validar_dades(candidato):
    condicoes = [
        candidato["Nombre"].isalpha(),
        candidato["Apellido"].isalpha(),
        str(candidato["Teléfono"]).isnumeric() and len(str(candidato["Teléfono"])) == 9,
        isinstance(candidato["Experiencia"], int) and 0 <= candidato["Experiencia"] <= 50,
        isinstance(candidato["Nivel de Catalan"], int) and 0 <= candidato["Nivel de Catalan"] <= 3,
        isinstance(candidato["Nivel de Excel"], int) and 0 <= candidato["Nivel de Excel"] <= 3,
        isinstance(candidato["Título académico"], int) and 0 <= candidato["Título académico"] <= 3,
    ]
    return all(condicoes)

# La función calcular_punctuacio() concatena los valores de experiencia,
# habilidades y educación del candidato, se asegura de que sean valores
# enteros y los suma según el peso de cada uno
def calcular_puntuacio(registro_candidatos):
  # El bucle itera a través de cada diccionario individualmente dentro de la lista
  for candidato in registro_candidatos:
      # Suma los valores utilizando los nombres de las claves
      suma = candidato["Nivel de Catalan"] + candidato["Nivel de Excel"] + candidato["Título académico"] + candidato["Experiencia"] * 1.5
      # Almacena el resultado en el último elemento del diccionario
      candidato["Puntuación"] = suma
  return registro_candidatos

# La función classificar_candidate() asigna una clasificación según el rango
# de puntuación de cada candidato y almacena los datos del registro del
# candidato en una nueva lista que contiene únicamente el nombre, apellido,
# número de teléfono y la clasificación final
def classificar_candidat(datos):
  classificacion = []
  for candidato in datos:
    if candidato["Puntuación"] >= 12:
      clas = "Prioridad Alta"
    elif 8 <= candidato["Puntuación"] < 12:
      clas = "Candidato adecuado"
    else:
      clas = "No prioritario"

    candidato_clasif = {
        "ID": candidato["ID"],
        "Nombre": candidato["Nombre"],
        "Apellido": candidato["Apellido"],
        "Teléfono": candidato["Teléfono"],
        "Puntuación": candidato["Puntuación"],
        "Classificación": clas
    }
    classificacion.append(candidato_clasif)
  return classificacion

# La función mostrar_individual() utiliza el metodo pprint.pprint() para
# imprimir la lista de registros candidatos obtenidos de la función get_dates()
# a medida que se registran
def mostrar_individual(registro):
  pprint.pprint(registro, sort_dicts=False)

# La función mostrar_informe(), basada en el valor de retorno de la función
# obtenir_dades(), imprime la lista de registros usando el metodo
# pprint.pprint() y ordena los candidatos de mayor a menor puntuación.
def mostrar_informe(registro):
  print("\n---------Informe de selección---------\n")
  pprint.pprint(classificar_candidat(registro), sort_dicts=False)


# La función obtenir_dades() recopila la entrada para cada candidato
#y la almacena en una lista de diccionarios.
def obtenir_dades():

  registro_candidatos = []

  registro_candidatos_test = [
    "Laura Serra", "608112233", 6, 3, 3, 3,
    "Clara Gómez", "655221199", 3, 3, 3, 2,
    "Sergio López", "644112211", 3, 2, 2, 2,
    "Candidat Error", "611000000", 5, 7, 3, 2, # Català = 7 → NO VÀLID
    "Marta Ruiz", "699887766", 2, 3, 2, 1,
    "Marc Vidal", "612443322", 6, 3, 3, 3,
    "Júlia Romero", "677998877", 5, 3, 3, 2,
    "Pol Navarro", "699554433", 4, 3, 2, 2,
    "David Ferrer", "677665544", 2, 1, 1, 1,
    "Anna Paredes", "633221144", 1, 2, 1, 0,
    "Anibal Paredes", "644272727", 1, 2, 1, 0,
    "Núria Casals", "600112200", 8, 2, 3, 3 # 11è candidat
    ]

  # Se utiliza un bucle for para limitar a 10 el número de candidatos que se pueden registrar.

  llaves = ["ID", "Nombre", "Segundo apellido", "Teléfono", "Experiencia", "Nivel de Catalan", "Nivel de Excel", "Título académico", "Puntuación"]
  tamano_registro = 6
  num_max_candidatos = 10
  for i in range(0, len(registro_candidatos_test), tamano_registro):
    if len(registro_candidatos) >= num_max_candidatos:
      print("\nLímite de 10 candidatos alcanzado.")
      break

    datos_candidato = registro_candidatos_test[i:i + tamano_registro]
    nombre, apellido = datos_candidato[0].split()

    candidato = {
        "ID": 0,
        "Nombre": str(nombre),
        "Apellido": str(apellido),
        "Teléfono": datos_candidato[1],
        "Experiencia": int(datos_candidato[2]),
        "Nivel de Catalan": int(datos_candidato[3]),
        "Nivel de Excel": int(datos_candidato[4]),
        "Título académico": int(datos_candidato[5]),
        "Puntuación": int(0)
    }
    if validar_dades(candidato):
      candidato["Teléfono"] = int(candidato["Teléfono"])
      registro_candidatos.append(candidato)
      calcular_puntuacio([candidato])
      print(f"\nCandidato válido registrado: {nombre} {apellido}")
      print(f"\nPuntuación: {candidato['Puntuación']}")

    else:
      print(f"\nCandidato inválido, no registrado: {nombre} {apellido}")

  for id, candidato in enumerate(registro_candidatos, start=1):
        candidato["ID"] = id

  # Aquí, las funciones validar_dades(), calcular_puntuacio() y
  # mostrar_individual() se llaman para cada registro.
  calcular_puntuacio(registro_candidatos)

  print("No se admiten más candidaturas.\n")
  registro_ordenado = sorted(registro_candidatos, key=lambda c: c["Puntuación"], reverse=True)
  return registro_ordenado

# Finalmente, se define la función main_seleccio(), que llama a las funciones
# obtenir_dades() y mostrar_informe() para que se ejecuten y generen
# el informe de selección final.
def main_seleccio():
  registro = obtenir_dades()
  mostrar_informe(registro)
# Aquí se ejecuta la función principal, main_seleccio().
main_seleccio()

Candidato válido registrado: Laura Serra

Puntuación: 18.0

Candidato válido registrado: Clara Gómez

Puntuación: 12.5

Candidato válido registrado: Sergio López

Puntuación: 10.5

Candidato inválido, no registrado: Candidat Error

Candidato válido registrado: Marta Ruiz

Puntuación: 9.0

Candidato válido registrado: Marc Vidal

Puntuación: 18.0

Candidato válido registrado: Júlia Romero

Puntuación: 15.5

Candidato válido registrado: Pol Navarro

Puntuación: 13.0

Candidato válido registrado: David Ferrer

Puntuación: 6.0

Candidato válido registrado: Anna Paredes

Puntuación: 4.5

Candidato válido registrado: Anibal Paredes

Puntuación: 4.5

Límite de 10 candidatos alcanzado.
No se admiten más candidaturas.


---------Informe de selección---------

[{'ID': 1,
  'Nombre': 'Laura',
  'Apellido': 'Serra',
  'Teléfono': 608112233,
  'Puntuación': 18.0,
  'Classificación': 'Prioridad Alta'},
 {'ID': 5,
  'Nombre': 'Marc',
  'Apellido': 'Vidal',
  'Teléfono': 612443322,
  'Puntuación': 18.0,
  'Classificación': 'Prioridad Alta'},
 {'ID': 6,
  'Nombre': 'Júlia',
  'Apellido': 'Romero',
  'Teléfono': 677998877,
  'Puntuación': 15.5,
  'Classificación': 'Prioridad Alta'},
 {'ID': 7,
  'Nombre': 'Pol',
  'Apellido': 'Navarro',
  'Teléfono': 699554433,
  'Puntuación': 13.0,
  'Classificación': 'Prioridad Alta'},
 {'ID': 2,
  'Nombre': 'Clara',
  'Apellido': 'Gómez',
  'Teléfono': 655221199,
  'Puntuación': 12.5,
  'Classificación': 'Prioridad Alta'},
 {'ID': 3,
  'Nombre': 'Sergio',
  'Apellido': 'López',
  'Teléfono': 644112211,
  'Puntuación': 10.5,
  'Classificación': 'Candidato adecuado'},
 {'ID': 4,
  'Nombre': 'Marta',
  'Apellido': 'Ruiz',
  'Teléfono': 699887766,
  'Puntuación': 9.0,
  'Classificación': 'Candidato adecuado'},
 {'ID': 8,
  'Nombre': 'David',
  'Apellido': 'Ferrer',
  'Teléfono': 677665544,
  'Puntuación': 6.0,
  'Classificación': 'No prioritario'},
 {'ID': 9,
  'Nombre': 'Anna',
  'Apellido': 'Paredes',
  'Teléfono': 633221144,
  'Puntuación': 4.5,
  'Classificación': 'No prioritario'},
 {'ID': 10,
  'Nombre': 'Anibal',
  'Apellido': 'Paredes',
  'Teléfono': 644272727,
  'Puntuación': 4.5,
  'Classificación': 'No prioritario'}]

Ejercicio 2: Segmentación por riesgo de cesta de compra

Alogoritmo:

- El código debe leer la lista de entradas con los datos de los clientes;
- Obtener el rango de edad y el factor de comportamiento;
- Calcular el riesgo para cada cliente;
- Organizar los datos en un DataFrame;
- Responder a las preguntas:
1. ¿Qué clientes deben contactar primero en una campaña de retargeting?
2. ¿Qué diferencias existen entre clientes con el mismo comportamiento pero de edades distintas? (Por ejemplo: ¿un cliente joven que abandona la cesta de compra hace 24 h tiene el mismo riesgo que uno de más edad?)
3. ¿Qué clientes presentan tan poco interés que no vale la pena invertir presupuesto?
4. ¿Qué cliente sería lo más rentable de recuperar?

In [61]:
# Esta biblioteca permite usar funciones estadísticas.
import scipy.stats as stats
# Estas bibliotecas permiten usar funciones matemáticas, de agrupación y creación de tablas.
import pandas as pd
import numpy as np
# Base de datos proporcionada.
clients = [
      {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
      {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
      {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
      {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
      {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
      {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
      {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
      {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
      {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
      {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
  ]

# La siguiente función recibe como argumento la lista de clientes y sus datos y devuelve la misma lista
# con los factores de comportamiento, de edad y el riesgo final calculado incorporados.
def processar_clients(clients):
    result_segments = []
    for cliente in clients:
      segment_info = obtenir_segment_i_factor(cliente["codi_comportament"])
      factot_edat = obtenir_factor_edat(cliente["grup_edat"])
      mensage = obtenir_factor_edat(cliente["grup_edat"])
      fac_codi = segment_info["factor"]
      fac_etad = factot_edat["factor"]
      risco = calcular_risc(fac_codi, fac_etad)

      datos_cliente = {
        "id_cliente": cliente["id_client"],
        "nombre": cliente["nom"],
        "edad": cliente["edat"],
        "grupo de edad": cliente["grup_edat"],
        "codigo_comportamiento": cliente["codi_comportament"],
        "segmento": segment_info["segmento"],
        "mensage": segment_info["mensage"],
        "factor_codigo": segment_info["factor"],
        "factor_edat": factot_edat["factor"],
        "riesgo_final": risco
      }

      result_segments.append(datos_cliente)
    return result_segments

# Esta función recibe como argumento cada iteración del bucle for de la función processar_clients()
# y funciona como un diccionario de búsqueda donde cada índice corresponde a un código de comportamiento
# de los clientes, devolviendo el segmento, el mensaje y el factor asociados.
def obtenir_segment_i_factor(codi_comportament):

  segments = {
      0: {"segmento": "Navega pero no añade productos",
          "factor": 0.1, "mensage": "Tu carrito de compras está vacío, ¡vamos a agregar algunos artículos!"},
      1: {"segmento": "Agregar productos pero no llega al checkout",
          "factor": 0.25, "mensage": "Todavía hay artículos en tu carrito pendientes de chekout, ¡no te olvides de ellos!"},
      2: {"segmento": "Llega al checkout pero no paga",
          "factor": 0.5, "mensage": "¡Ya casi lo tienes, solo falta pagar!"},
      3: {"segmento": "Cesta de compra abandonado hace menos de 24 h",
          "factor": 0.75, "mensage": "¡Tu cesta de la compra te está esperando!"},
      4: {"segmento": "Cesta de compra abandonado hace más de 24 h",
          "factor": 0.9, "mensage": "¡Tu cesta de la compra lleva esperándote más de 24 horas, no te rindas!"}
      }

  return segments[codi_comportament]

# Esta función recibe como argumento el grupo de edad del cliente en cada iteración
# del bucle for de la función processar_clients() y funciona como un diccionario de
# búsqueda donde cada índice corresponde a un rango de edad de los clientes,
# devolviendo el factor asociado.
def obtenir_factor_edat(grup_edat):

  factor_edad = {
      "18-25": {"factor": 1.2},
      "26-40": {"factor": 1.0},
      "41-60": {"factor": 0.85},
      "60+": {"factor": 0.7}
      }
  return factor_edad[grup_edat]

# Esta función recibe como argumento el factor de código y el factor de edad
# del cliente en cada iteración del bucle for de la función processar_clients(), multiplica
# ambos factores y devuelve el valor del riesgo final de cada cliente.
def calcular_risc(factor_codigo, factor_edad):
  risc_final = round((factor_codigo * factor_edad), 2)
  return risc_final

# La siguiente función convierte en un dataframe la lista de diccionarios result_segments = [] creada
# dentro de la función processar_clients(clients), ordena de forma descendente los valores
# de riesgo_final y devuelve el dataframe generado.
def mostrar_dataframe(df_input):
    df = pd.DataFrame(df_input)
    df_ordenado = df.sort_values(["riesgo_final"], ascending=[False])
    return df_ordenado

# Esta función responde a las preguntas de la campaña de retargeting de acuerdo con los
# datos obtenidos en el dataframe.
def mostrar_respostes(df):
    #¿Qué clientes deben contactar primero en una campaña de retargeting?
    print("------------------------------Campaña de retargeting------------------------------")
    print("Necesitamos contactar a los siguientes clientes en nuestra campaña de retargeting: \n")
    primeros = df[["id_cliente", "nombre", "riesgo_final"]]
    print(primeros.head(3))

    print("----------------------------------------------------------------------------------")
    #¿Qué diferencias existen entre clientes con el mismo comportamiento
    # pero de edades distintas? (Por ejemplo: ¿un cliente joven que abandona
    # la cesta de compra hace 24 h tiene el mismo riesgo que uno de más edad?)
    corr, _ = stats.pearsonr (df["edad"], df["codigo_comportamiento"])
    print("No existe una correlación muy fuerte entre la edad y el comportamiento del cliente. \n")
    print("Correlación (R):" , round(corr, 2))

    print("----------------------------------------------------------------------------------")
    #¿Qué clientes presentan tan poco interés que no vale la pena invertir presupuesto?
    print("No merece la pena incluir a los siguientes clientes en la campaña: \n")
    primeros = df[["id_cliente", "nombre", "riesgo_final"]]
    print(primeros.tail(3))

    print("----------------------------------------------------------------------------------")
    #¿Qué cliente sería lo más rentable de recuperar?
    print("Dado que no existe una correlación muy fuerte entre la edad y el comportamiento, \nlos clientes con mayor potencial de compra son aquellos cuyo código de comportamiento \nes igual a 2: llegan al pago pero no finalizan la compra.\n")
    mas_criticos = df.loc[df["codigo_comportamiento"] == 2,["id_cliente", "nombre", "codigo_comportamiento", "riesgo_final"]]
    print(mas_criticos)

# Por último, esta función recibe como argumento la base de datos proporcionada y orquesta
# la ejecución de las demás funciones anteriores.
def main_marketing(clients):

  df_input = processar_clients(clients)
  df_ordenado = mostrar_dataframe(df_input)
  mostrar_respostes(df_ordenado)
  print("\nDatos de los clientes: \n")
  return df_ordenado

main_marketing(clients)

------------------------------Campaña de retargeting------------------------------
Necesitamos contactar a los siguientes clientes en nuestra campaña de retargeting:

   id_cliente        nombre  riesgo_final
0           1   Laura Serra          1.08
9          10   Núria Costa          0.90
4           5  Mónica Pérez          0.77
----------------------------------------------------------------------------------
No existe una correlación muy fuerte entre la edad y el comportamiento del cliente.

Correlación (R): 0.03
----------------------------------------------------------------------------------
No merece la pena incluir a los siguientes clientes en la campaña:

   id_cliente        nombre  riesgo_final
8           9  Diego Romero          0.30
5           6   Luis García          0.21
7           8    Eva Martín          0.10
----------------------------------------------------------------------------------
Dado que no existe una correlación muy fuerte entre la edad y el comportamiento,
los clientes con mayor potencial de compra son aquellos cuyo código de comportamiento
es igual a 2: llegan al pago pero no finalizan la compra.

   id_cliente      nombre  codigo_comportamiento  riesgo_final
3           4  Joan Riera                      2           0.6
2           3   Ana López                      2           0.5

Datos de los clientes:

,id_cliente,nombre,edad,grupo de edad,codigo_comportamiento,segmento,mensage,factor_codigo,factor_edat,riesgo_final
0,1,Laura Serra,23,18-25,4,Cesta de compra abandonado hace más de 24 h,¡Tu cesta de la compra lleva esperándote más d...,0.90,1.20,1.08
9,10,Núria Costa,33,26-40,4,Cesta de compra abandonado hace más de 24 h,¡Tu cesta de la compra lleva esperándote más d...,0.90,1.00,0.90
4,5,Mónica Pérez,47,41-60,4,Cesta de compra abandonado hace más de 24 h,¡Tu cesta de la compra lleva esperándote más d...,0.90,0.85,0.77
1,2,Marc Vidal,35,26-40,3,Cesta de compra abandonado hace menos de 24 h,¡Tu cesta de la compra te está esperando!,0.75,1.00,0.75
3,4,Joan Riera,19,18-25,2,Llega al checkout pero no paga,"¡Ya casi lo tienes, solo falta pagar!",0.50,1.20,0.60
6,7,Pilar Sánchez,61,60+,3,Cesta de compra abandonado hace menos de 24 h,¡Tu cesta de la compra te está esperando!,0.75,0.70,0.52
2,3,Ana López,29,26-40,2,Llega al checkout pero no paga,"¡Ya casi lo tienes, solo falta pagar!",0.50,1.00,0.50
8,9,Diego Romero,24,18-25,1,Agregar productos pero no llega al checkout,Todavía hay artículos en tu carrito pendientes...,0.25,1.20,0.30
5,6,Luis García,52,41-60,1,Agregar productos pero no llega al checkout,Todavía hay artículos en tu carrito pendientes...,0.25,0.85,0.21
7,8,Eva Martín,38,26-40,0,Navega pero no añade productos,"Tu carrito de compras está vacío, ¡vamos a agr...",0.10,1.00,0.10

#Nivel 2

Ejercicio 1: Gestión de riesgo y priorización de pacientes

In [62]:
# Esta biblioteca permite imprimir diccionarios en vertical para una mejor visualización.
import pprint
# Estas bibliotecas permiten usar funciones matemáticas, de agrupación y creación de tablas.
import pandas as pd
import numpy as np
# Base de datos proporcionada.
pacients = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho", #  3 + 4 + 1 = 8
    "Luis|33|dolor_cabeza,faTiga", # 1 + 1 = 2
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos", # 3 + 5 + 1 = 9
    "Jordi|52|fatiga , tos", # 1 + 1 = 2
    "Anna|29|fiebre alta,dolor_cabeza" # 3 + 1 = 4
]
# Esta función asocia el valor de riesgo a los síntomas de cada paciente y calcula
# el valor total del riesgo.
def riesgos(sintomas):
  nivells_risc = {
      "fiebre_alta": 3,
      "dificultad_respirar": 5,
      "dolor_pecho": 4,
      "tos": 1,
      "fatiga": 1,
      "dolor_cabeza": 1
      }
  valor_riesgo = 0
  for riesgo in nivells_risc:
    if riesgo in sintomas:
      valor_riesgo = valor_riesgo + nivells_risc[riesgo]
  return valor_riesgo

# Esta función convierte la lista de pacientes en un dataframe ordenado por el valor del
# riesgo total de cada paciente.
def mostrar_dataframe(lista_pacients):
  df = pd.DataFrame(lista_pacients)
  df_ordenado = df.sort_values(["riesgo_total"], ascending=[False])
  return df_ordenado

# Esta función convierte la lista de strings con la información de cada paciente en
# una lista de diccionarios y normaliza los datos para poder compararlos
# con los valores predeterminados de los síntomas listados en la base de datos.
def convertir_y_normalizar_datos(pacients):
  lista_pacients = []
  for i in range(len(pacients)):
    pacients[i] = pacients[i].replace("|",",")
    pacients[i] = pacients[i].split(",")

    if len(pacients[i]) == 4:
        convertido = {
          "Id": 0,
          "nombre": (pacients[i][0]).strip(),
          "edad": (pacients[i][1]).strip(),
          "sintomas normalizados": [s.strip().lower().replace(" ", "_") for s in pacients[i][2:]],
          "riesgo_total": 0
          }
        lista_pacients.append(convertido)
    else:
        convertido = {
          "Id": 0,
          "nombre": (pacients[i][0]).strip(),
          "edad": (pacients[i][1]).strip(),
          "sintomas normalizados": [s.strip().lower().replace(" ", "_") for s in pacients[i][2:]],
          "riesgo_total": 0
          }
        lista_pacients.append(convertido)
  return lista_pacients

# La función principal orquesta las demás funciones, establece un id para cada paciente
# y devuelve el dataframe procesado al final.
def main_pacientes(pacients):
  lista_pacients = convertir_y_normalizar_datos(pacients)
  contador_id = 0
  for paciente in lista_pacients:
    contador_id += 1
    paciente["Id"] = contador_id
    paciente["riesgo_total"] = riesgos(paciente["sintomas normalizados"])
  df_pacientes = mostrar_dataframe(lista_pacients)
  print("Lista de pacientes ordenados por el riesgo total:\n")
  return df_pacientes

main_pacientes(pacients)

Lista de pacientes ordenados por el riesgo total:

   Id nombre edad                    sintomas normalizados  riesgo_total
2   3   Sara   67  [fiebre_alta, dificultad_respirar, tos]             9
0   1  Maria   45          [tos, fiebre_alta, dolor_pecho]             8
4   5   Anna   29              [fiebre_alta, dolor_cabeza]             4
1   2   Luis   33                   [dolor_cabeza, fatiga]             2
3   4  Jordi   52                            [fatiga, tos]             2

Ejercicio 2: Clasificación de clientes de seguros

In [63]:
# Esta biblioteca permite imprimir diccionarios en vertical para una mejor visualización.
import pprint
# Esta biblioteca permite usar funciones estadísticas.
import scipy.stats as stats
# Estas bibliotecas permiten usar funciones matemáticas, de agrupación y creación de tablas.
import pandas as pd
import numpy as np
# Base de datos proporcionada.

clients = [
    {"nombre": "Ana", "edad": 42, "codigo": 0},  # precio final = 120 * (1 + 42/100) = 170.4
    {"nombre": "Carlos", "edad": 30, "codigo": 2}, # precio final = 350 * (1 + 30/100) = 455
    {"nombre": "Isabel", "edad": 55, "codigo": 3}, # precio final = 500 * (1 + 55/100) = 775
    {"nombre": "Jorge", "edad": 40, "codigo": 1}, # precio final = 200 * (1 + 40/100) = 280
    {"nombre": "Marta", "edad": 28, "codigo": 0} # precio final = 120 * (1 + 28/100) = 153.6
]

# Esta función asocia el valor del código del seguro de cada cliente con la categoría,
# el precio base y la probabilidad de fraude, y lo devuelve según el cliente elegido.
def obtener_nivel(codigo):

  nivells_seguro = {
    0: {"categoria": "Riesgo bajo", "precio_base": 120, "prob_fraude": 0.01},
    1: {"categoria": "Riesgo medio", "precio_base": 200, "prob_fraude": 0.05},
    2: {"categoria": "Riesgo alto", "precio_base": 350, "prob_fraude": 0.15},
    3: {"categoria": "Riesgo crítico", "precio_base": 500, "prob_fraude": 0.30}
    }
  return nivells_seguro[codigo]

# Esta función calcula el precio final de cada cliente y añade a cada registro
# el elemento precio_final, devolviendo la lista actualizada de clientes.
def precio_seguro(clients):
  for cliente in clients:
    precio_base = cliente["precio_base"]
    edad = cliente["edad"]
    precio_final = precio_base * (1 + edad/100)
    cliente.update({"precio_final": precio_final})
  return(clients)

# Esta función convierte la lista de registros en un dataframe, organiza la disposición de las columnas
# y ordena las filas a partir del valor de precio_base.
def mostrar_dataframe(clients):

  df = pd.DataFrame(clients)
  df_ordenado = df.sort_values(["precio_base"], ascending=[False])
  df_ordenado = df_ordenado[["Id", "nombre", "edad", "codigo", "categoria", "prob_fraude", "precio_base", "precio_final"]]
  return df_ordenado

# Esta función realiza un análisis estadístico simplificado de las relaciones entre edad,
# precio y probabilidad de fraude para cada cliente.
def analisis_seguro(df):
  corr_edad, _ = stats.pearsonr (df["edad"], df["prob_fraude"])
  corr_precio_final, _ = stats.pearsonr (df["precio_final"], df["prob_fraude"])
  print("Correlación probabilidad de fraude x edad (R):" , round(corr_edad, 2))
  print("Correlación probabilidad de fraude x precio final (R):" , round(corr_precio_final, 2))
  print("El siguiente cliente presentó la mayor probabilidad de cometer fraude, \ny se observa a través de la correlación de Pearson (R) que este es precisamente \nel que tiene el precio final del seguro más alto y, por lo tanto, debe ser revisado manualmente.\n\n", df.iloc[0])


# La función principal orquesta las demás funciones y devuelve el análisis del cliente
# más crítico y el dataframe de los clientes ordenados por criticidad.
def main_seguros(clients):

  contador_id = 0
  for cliente in clients:
    contador_id += 1
    cliente["Id"] = contador_id
    nivel = obtener_nivel(cliente["codigo"])
    cliente.update(nivel)
  precio_seguro(clients)
  mostrar_dataframe(clients)
  df = mostrar_dataframe(clients)
  analisis_seguro(df)
  print("\n\nLista de clientes oredenados por riesgo de fraude\n")
  return df

main_seguros(clients)

Correlación probabilidad de fraude x edad (R): 0.64
Correlación probabilidad de fraude x precio final (R): 1.0
El siguiente cliente presentó la mayor probabilidad de cometer fraude,
y se observa a través de la correlación de Pearson (R) que este es precisamente
el que tiene el precio final del seguro más alto y, por lo tanto, debe ser revisado manualmente.

 Id                           3
nombre                  Isabel
edad                        55
codigo                       3
categoria       Riesgo crítico
prob_fraude                0.3
precio_base                500
precio_final             775.0
Name: 2, dtype: object


Lista de clientes oredenados por riesgo de fraude

,Id,nombre,edad,codigo,categoria,prob_fraude,precio_base,precio_final
2,3,Isabel,55,3,Riesgo crítico,0.30,500,775.0
1,2,Carlos,30,2,Riesgo alto,0.15,350,455.0
3,4,Jorge,40,1,Riesgo medio,0.05,200,280.0
0,1,Ana,42,0,Riesgo bajo,0.01,120,170.4
4,5,Marta,28,0,Riesgo bajo,0.01,120,153.6

#Nivel 3

Ejercicio 1: Generador de contraseñas seguras

In [64]:
# Esta biblioteca permite usar funciones matemáticas y, en este código en especial,
# la función random.
import numpy as np
# Esta biblioteca permite usar funciones para la manipulación de strings.
import string

# Esta función establece los parámetros de la contraseña que se va a crear.
def parametros():

  # Estos son los valores por defecto.
  mayusculas = True
  minusculas = True
  numeros = True
  simbolos = False

  # Para cada elección de parámetros el usuario debe elegir entre "S" y "N",
  # de lo contrario se le vuelve a pedir una respuesta.
  verif_param = 0
  while verif_param == 0:
    verif_param = 0
    usar_param = input("¿Desea modificar los parámetros de la contrsaseña? S/N\n").upper()
    if usar_param == "S":
      verif = 0
      while verif == 0:
        incluir_may = input("¿Desea incluir letras mayúsculas en la contraseña? S/N\n").upper()
        if incluir_may == "S":
          mayusculas = True
          verif = 1
        elif incluir_may == "N":
          mayusculas = False
          verif = 1
        else:
          print("entrada invaida!\n")

      verif = 0
      while verif == 0:
        incluir_may = input("¿Desea incluir letras minúsculas en la contraseña? S/N\n").upper()
        if incluir_may == "S":
          minusculas = True
          verif = 1
        elif incluir_may == "N":
          minusculas = False
          verif = 1
        else:
          print("entrada invalida!\n")

      verif = 0
      while verif == 0:
        incluir_may = input("¿Desea incluir numeros en la contraseña? S/N\n").upper()
        if incluir_may == "S":
          numeros = True
          verif = 1
        elif incluir_may == "N":
          numeros = False
          verif = 1
        else:
          print("entrada invalida!\n")

      verif = 0
      while verif == 0:
        incluir_may = input("¿Desea incluir símbolos en la contraseña? S/N\n").upper()
        if incluir_may == "S":
          simbolos = True
          verif = 1
        elif incluir_may == "N":
          simbolos = False
          verif = 1
        else:
          print("Entrada invalida!\n")
      # En caso de que el usuario no elija ningún parámetro para la contraseña, el bucle
      # vuelve a preguntar, exigiendo que se elija al menos un parámetro.
      if (mayusculas == False) and (minusculas == False) and (numeros == False) and (simbolos == False):
        print("Al menos un parametro tiene que ser elegido.\n")
        verif_param = 0
      else:
        verif_param = 1

      print("Contrasena generada: ")
    elif usar_param == "N":
      print("Parámetros mantenidos.\n")
      print("Contrasena generada: ")
      verif_param = 1
    else:
      print("Entrada invalida!\n")

  return (mayusculas, minusculas, numeros, simbolos)

# Esta función recibe como parámetros los valores de los parámetros de contraseña elegidos
# y genera una contraseña aleatoria que cumple con los requisitos deseados.
def generador(param):
  # Aquí se establece el tamaño de la contraseña entre 6 y 9 caracteres.
  tamano = np.random.randint(6, 10)

  # Esta lista define todos los posibles caracteres que se pueden usar según los
  # parámetros elegidos.
  aux = []
  if param[0]:
    aux.append(string.ascii_uppercase)
  if param[1]:
    aux.append(string.ascii_lowercase)
  if param[2]:
    aux.append(string.digits)
  if param[3]:
    aux.append(string.punctuation)
  # Se convierten las listas de los caracteres que se van a usar en un array.
  alfabeto = np.array(list("".join(aux)))
  # Se define aleatoriamente un carácter de cada lista elegida.
  obrigatorios = np.array([np.random.choice(list(g)) for g in aux])
  # Según el tamaño de la contraseña, se completa el resto con caracteres
  # elegidos aleatoriamente.
  restantes = np.random.choice(alfabeto, size=tamano - len(aux))

  # Se concatenan los caracteres obligatorios con los restantes, se mezclan
  # aleatoriamente los caracteres y por último se convierten en un string final.
  contrasena = "".join(np.random.permutation(np.concatenate([obrigatorios, restantes])))

  return contrasena
# La función principal orquesta la ejecución de las demás funciones y devuelve la contraseña generada.
def main_contrasena():

  param = parametros()
  contrasena = generador(param)

  return contrasena

main_contrasena()

¿Desea modificar los parámetros de la contrsaseña? S/N
n
Parámetros mantenidos.

Contrasena generada:

'm0ktTIXo'